(part "IRFR010PBF-BE3"
    (packageRef "SQD30N0520L_GE3")
    (interface
        (port "1" (symbPinId 1) (portName "G") (portType INOUT))
        (port "2" (symbPinId 2) (portName "D") (portType INOUT))
        (port "3" (symbPinId 3) (portName "S") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Manufacturer_Name" "Vishay")
    (property "Manufacturer_Part_Number" "IRFR010PBF-BE3")
    (property "Mouser_Part_Number" "78-IRFR010PBF-BE3")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Vishay-Siliconix/IRFR010PBF-BE3?qs=zW32dvEIR3sojEq2SMtqHw%3D%3D")
    (property "Arrow_Part_Number" "IRFR010PBF-BE3")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/irfr010pbf-be3/vishay?region=nac")
    (property "Description" "MOSFET 60V  N-CH HEXFET MOSFET D-PAK")
    (property "Datasheet_Link" "https://www.vishay.com/docs/91420/sihfr010.pdf")
    (property "symbolName1" "IRFR010PBF-BE3")
)
