M48
; DRILL file {KiCad 9.0.9} date 2026-09-18T14:06:58-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-18T14:06:58-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.9
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.400
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C1.190
%
G90
G05
T1
X72.0Y-61.0
T2
X73.46Y-65.0
X76.0Y-65.0
M30
